// ECO code → opening name lookup table
// Covers all standard ECO codes A00–E99
export const ECO_NAMES = {
  // ── A: Flank / English / Dutch ────────────────────────────────
  A00: "Uncommon Opening",
  A01: "Nimzo-Larsen Attack",
  A02: "Bird's Opening",
  A03: "Bird's Opening, Dutch Variation",
  A04: "Réti Opening",
  A05: "Réti Opening",
  A06: "Réti Opening, Old Indian Attack",
  A07: "King's Indian Attack",
  A08: "King's Indian Attack, Symmetrical Defense",
  A09: "Réti Opening, Advance Variation",
  A10: "English Opening",
  A11: "English Opening, Caro-Kann Defensive System",
  A12: "English Opening, Caro-Kann Defensive System",
  A13: "English Opening",
  A14: "English Opening, Neo-Catalan Declined",
  A15: "English Opening, Anglo-Indian Defense",
  A16: "English Opening, Anglo-Grünfeld Defense",
  A17: "English Opening, Anglo-Indian Defense",
  A18: "English Opening, Mikenas-Carls Variation",
  A19: "English Opening, Mikenas-Carls, Sicilian Variation",
  A20: "English Opening",
  A21: "English Opening, Kramnik-Shirov Attack",
  A22: "English Opening, Two Knights Variation",
  A23: "English Opening, Bremen System, Keres Variation",
  A24: "English Opening, Bremen System with ...g6",
  A25: "English Opening, Closed System",
  A26: "English Opening, Closed, Full Symmetry",
  A27: "English Opening, Three Knights System",
  A28: "English Opening, Four Knights System",
  A29: "English Opening, Four Knights, Kingside Fianchetto",
  A30: "English Opening, Symmetrical Variation",
  A31: "English Opening, Symmetrical, Benoni Formation",
  A32: "English Opening, Symmetrical, Two Knights Variation",
  A33: "English Opening, Symmetrical, Four Knights Variation",
  A34: "English Opening, Symmetrical, Three Knights Variation",
  A35: "English Opening, Symmetrical, Four Knights System",
  A36: "English Opening, Symmetrical, Four Knights, Fianchetto",
  A37: "English Opening, Symmetrical, Two Knights, Fianchetto",
  A38: "English Opening, Symmetrical Variation",
  A39: "English Opening, Symmetrical, Main Line with d4",
  A40: "Queen's Pawn Opening",
  A41: "Old Indian Defense",
  A42: "Old Indian Defense, Pawn Center Variation",
  A43: "Benoni Defense, Old Benoni",
  A44: "Old Benoni Defense",
  A45: "Indian Defense, Trompowsky Attack",
  A46: "Indian Defense, Torre Attack",
  A47: "Indian Defense, London System",
  A48: "King's Indian Defense, East Indian Variation",
  A49: "King's Indian Defense, Fianchetto Variation",
  A50: "Indian Defense, Normal Variation",
  A51: "Budapest Defense",
  A52: "Budapest Defense, Rubinstein Variation",
  A53: "Old Indian Defense",
  A54: "Old Indian Defense, Ukrainian Variation",
  A55: "Old Indian Defense, Main Line",
  A56: "Benoni Defense",
  A57: "Benko Gambit",
  A58: "Benko Gambit Accepted",
  A59: "Benko Gambit, Full Variation",
  A60: "Benoni Defense",
  A61: "Benoni Defense, Nimzovich Variation",
  A62: "Benoni Defense, Fianchetto Variation",
  A63: "Benoni Defense, Fianchetto, 9...Nbd7",
  A64: "Benoni Defense, Fianchetto, 11...Re8",
  A65: "Benoni Defense, 6.e4",
  A66: "Benoni Defense, Pawn Storm Variation",
  A67: "Benoni Defense, Taimanov Variation",
  A68: "Benoni Defense, Four Pawns Attack",
  A69: "Benoni Defense, Four Pawns Attack, Main Line",
  A70: "Benoni Defense, Classical with 7.Nf3",
  A71: "Benoni Defense, Classical, 8.Bg5",
  A72: "Benoni Defense, Classical, 9.O-O",
  A73: "Benoni Defense, Classical, 9.O-O c5",
  A74: "Benoni Defense, Classical, 9...a6, 10.a4",
  A75: "Benoni Defense, Classical, 9...a6, 10.Bd3",
  A76: "Benoni Defense, Classical, 9...Re8",
  A77: "Benoni Defense, Classical, 9...Re8, 10.Nd2",
  A78: "Benoni Defense, Classical with ...Re8 and ...Na6",
  A79: "Benoni Defense, Classical, 11.f3",
  A80: "Dutch Defense",
  A81: "Dutch Defense",
  A82: "Dutch Defense, Staunton Gambit",
  A83: "Dutch Defense, Staunton Gambit, Staunton's Line",
  A84: "Dutch Defense",
  A85: "Dutch Defense, with c4 & Nc3",
  A86: "Dutch Defense, Leningrad System",
  A87: "Dutch Defense, Leningrad, 6.Nf3",
  A88: "Dutch Defense, Leningrad, 7.Nc3 c6",
  A89: "Dutch Defense, Leningrad, 7.Nc3 Nc6",
  A90: "Dutch Defense, Queen's Bishop Variation",
  A91: "Dutch Defense, 2.c4 Nf6",
  A92: "Dutch Defense",
  A93: "Dutch Defense, Stonewall, Botvinnik Variation",
  A94: "Dutch Defense, Stonewall with Ba3",
  A95: "Dutch Defense, Stonewall",
  A96: "Dutch Defense, Classical Variation",
  A97: "Dutch Defense, Ilyin-Genevsky Variation",
  A98: "Dutch Defense, Ilyin-Genevsky, Qc2",
  A99: "Dutch Defense, Ilyin-Genevsky, Burnett Variation",

  // ── B: Semi-open games (not 1.e4 e5) ─────────────────────────
  B00: "King's Pawn Opening",
  B01: "Scandinavian Defense",
  B02: "Alekhine's Defense",
  B03: "Alekhine's Defense, Four Pawns Attack",
  B04: "Alekhine's Defense, Modern Variation",
  B05: "Alekhine's Defense, Modern, 5.exd6",
  B06: "Modern Defense",
  B07: "Pirc Defense",
  B08: "Pirc Defense, Classical System",
  B09: "Pirc Defense, Austrian Attack",
  B10: "Caro-Kann Defense",
  B11: "Caro-Kann Defense, Two Knights Variation",
  B12: "Caro-Kann Defense",
  B13: "Caro-Kann Defense, Exchange Variation",
  B14: "Caro-Kann Defense, Panov-Botvinnik Attack",
  B15: "Caro-Kann Defense",
  B16: "Caro-Kann Defense, Bronstein-Larsen Variation",
  B17: "Caro-Kann Defense, Steinitz Variation",
  B18: "Caro-Kann Defense, Classical Variation",
  B19: "Caro-Kann Defense, Classical, 7...Nd7",
  B20: "Sicilian Defense",
  B21: "Sicilian Defense, Grand Prix Attack",
  B22: "Sicilian Defense, Alapin Variation",
  B23: "Sicilian Defense, Closed",
  B24: "Sicilian Defense, Closed, Smyslov Variation",
  B25: "Sicilian Defense, Closed, 6.f4",
  B26: "Sicilian Defense, Closed, 6.Be3",
  B27: "Sicilian Defense, Hungarian Variation",
  B28: "Sicilian Defense, O'Kelly Variation",
  B29: "Sicilian Defense, Nimzovich Variation",
  B30: "Sicilian Defense, Old Sicilian",
  B31: "Sicilian Defense, Nimzovich-Rossolimo Attack",
  B32: "Sicilian Defense, Löwenthal Variation",
  B33: "Sicilian Defense, Sveshnikov Variation",
  B34: "Sicilian Defense, Accelerated Dragon",
  B35: "Sicilian Defense, Accelerated Dragon, Modern Bc4",
  B36: "Sicilian Defense, Accelerated Dragon, Maróczy Bind",
  B37: "Sicilian Defense, Accelerated Dragon, Maróczy Bind, 5...Bg7",
  B38: "Sicilian Defense, Accelerated Dragon, Maróczy Bind, 6.Be3",
  B39: "Sicilian Defense, Accelerated Dragon, Maróczy Bind, Breyer Variation",
  B40: "Sicilian Defense",
  B41: "Sicilian Defense, Kan Variation",
  B42: "Sicilian Defense, Kan, 5.Bd3",
  B43: "Sicilian Defense, Kan, 5.Nc3",
  B44: "Sicilian Defense, Taimanov Variation",
  B45: "Sicilian Defense, Taimanov, American Attack",
  B46: "Sicilian Defense, Taimanov Variation",
  B47: "Sicilian Defense, Taimanov (Bastrikov) Variation",
  B48: "Sicilian Defense, Taimanov Variation",
  B49: "Sicilian Defense, Taimanov Variation",
  B50: "Sicilian Defense",
  B51: "Sicilian Defense, Moscow Variation",
  B52: "Sicilian Defense, Moscow, 3...Bd7",
  B53: "Sicilian Defense, Chekhover Variation",
  B54: "Sicilian Defense",
  B55: "Sicilian Defense, Prins Variation",
  B56: "Sicilian Defense",
  B57: "Sicilian Defense, Sozin Attack",
  B58: "Sicilian Defense, Classical",
  B59: "Sicilian Defense, Boleslavsky Variation",
  B60: "Sicilian Defense, Richter-Rauzer Attack",
  B61: "Sicilian Defense, Richter-Rauzer, 7.Qd2",
  B62: "Sicilian Defense, Richter-Rauzer, 6...e6",
  B63: "Sicilian Defense, Richter-Rauzer Attack",
  B64: "Sicilian Defense, Richter-Rauzer, 7...Be7",
  B65: "Sicilian Defense, Richter-Rauzer, ...a6 Variation",
  B66: "Sicilian Defense, Richter-Rauzer, 7...a6",
  B67: "Sicilian Defense, Richter-Rauzer, 7...a6, 8.f4",
  B68: "Sicilian Defense, Richter-Rauzer, 7...a6, 9.f4 Be7",
  B69: "Sicilian Defense, Richter-Rauzer, 7...a6 Defense",
  B70: "Sicilian Defense, Dragon Variation",
  B71: "Sicilian Defense, Dragon, Levenfish Variation",
  B72: "Sicilian Defense, Dragon, 6.Be3",
  B73: "Sicilian Defense, Dragon, Classical Variation",
  B74: "Sicilian Defense, Dragon, Classical, 9.Nb3",
  B75: "Sicilian Defense, Dragon, Yugoslav Attack",
  B76: "Sicilian Defense, Dragon, Yugoslav Attack, 7...O-O",
  B77: "Sicilian Defense, Dragon, Yugoslav Attack, 9.Bc4",
  B78: "Sicilian Defense, Dragon, Yugoslav Attack, 10.O-O-O",
  B79: "Sicilian Defense, Dragon, Yugoslav Attack, 12.h4",
  B80: "Sicilian Defense, Scheveningen Variation",
  B81: "Sicilian Defense, Scheveningen, Keres Attack",
  B82: "Sicilian Defense, Scheveningen, 6.f4",
  B83: "Sicilian Defense, Scheveningen, 6.Be2",
  B84: "Sicilian Defense, Scheveningen, Classical Variation",
  B85: "Sicilian Defense, Scheveningen, Classical, Main Line",
  B86: "Sicilian Defense, Sozin Attack, 6.Bc4",
  B87: "Sicilian Defense, Sozin Attack, Flank Variation",
  B88: "Sicilian Defense, Sozin Attack, Leonhardt Variation",
  B89: "Sicilian Defense, Sozin, 6...e6 7.Qe2",
  B90: "Sicilian Defense, Najdorf Variation",
  B91: "Sicilian Defense, Najdorf, Zagreb (Fianchetto) Variation",
  B92: "Sicilian Defense, Najdorf, Opocensky Variation",
  B93: "Sicilian Defense, Najdorf, 6.f4",
  B94: "Sicilian Defense, Najdorf, 6.Bg5",
  B95: "Sicilian Defense, Najdorf, 6...e6",
  B96: "Sicilian Defense, Najdorf, 7.f4",
  B97: "Sicilian Defense, Najdorf, 7...Qb6",
  B98: "Sicilian Defense, Najdorf, 7...Be7",
  B99: "Sicilian Defense, Najdorf, 7...Be7, Main Line",

  // ── C: Open games (1.e4 e5) ───────────────────────────────────
  C00: "French Defense",
  C01: "French Defense, Exchange Variation",
  C02: "French Defense, Advance Variation",
  C03: "French Defense, Tarrasch, 3...Nf6",
  C04: "French Defense, Tarrasch, Guimard Main Line",
  C05: "French Defense, Tarrasch, Closed Variation",
  C06: "French Defense, Tarrasch, Closed, Main Line",
  C07: "French Defense, Tarrasch with 3...c5",
  C08: "French Defense, Tarrasch, Open, 4.exd5 exd5",
  C09: "French Defense, Tarrasch, Open Variation, Main Line",
  C10: "French Defense, Paulsen Variation",
  C11: "French Defense, Classical",
  C12: "French Defense, MacCutcheon Variation",
  C13: "French Defense, Classical, Tartakower Variation",
  C14: "French Defense, Classical Variation",
  C15: "French Defense, Winawer, Fingerslip Variation",
  C16: "French Defense, Winawer, Advance Variation",
  C17: "French Defense, Winawer, Advance, 5.Bd2",
  C18: "French Defense, Winawer, Advance, Poisoned Pawn",
  C19: "French Defense, Winawer, Advance, 6...Ne7",
  C20: "King's Pawn Game",
  C21: "Center Game",
  C22: "Center Game, Paulsen Attack",
  C23: "Bishop's Opening",
  C24: "Bishop's Opening, Berlin Defense",
  C25: "Vienna Game",
  C26: "Vienna Game, Vienna Gambit",
  C27: "Vienna Game, Stanley Variation",
  C28: "Vienna Game",
  C29: "Vienna Gambit, Kaufmann Variation",
  C30: "King's Gambit",
  C31: "King's Gambit Declined, Falkbeer Counter Gambit",
  C32: "King's Gambit Declined, Falkbeer, 5.de5",
  C33: "King's Gambit Accepted",
  C34: "King's Gambit Accepted, King's Knight Gambit",
  C35: "King's Gambit Accepted, Cunningham Defense",
  C36: "King's Gambit Accepted, Abbazia Defense",
  C37: "King's Gambit Accepted, Quaade Gambit",
  C38: "King's Gambit Accepted, Hanstein Gambit",
  C39: "King's Gambit Accepted, Allgaier Gambit",
  C40: "King's Knight Opening",
  C41: "Philidor Defense",
  C42: "Petrov's Defense",
  C43: "Petrov's Defense, Modern Attack",
  C44: "King's Pawn Game",
  C45: "Scotch Game",
  C46: "Three Knights Game",
  C47: "Four Knights Game, Scotch Variation",
  C48: "Four Knights Game, Spanish Variation",
  C49: "Four Knights Game, Double Ruy Lopez",
  C50: "Italian Game",
  C51: "Evans Gambit",
  C52: "Evans Gambit, 5.c3 Ba5",
  C53: "Italian Game, Classical Variation",
  C54: "Italian Game, Classical, Greco Attack",
  C55: "Italian Game, Two Knights Defense",
  C56: "Two Knights Defense",
  C57: "Two Knights Defense, Fried Liver Attack",
  C58: "Two Knights Defense, Polerio Gambit",
  C59: "Two Knights Defense, Knorre Variation",
  C60: "Ruy Lopez",
  C61: "Ruy Lopez, Bird's Defense",
  C62: "Ruy Lopez, Old Steinitz Defense",
  C63: "Ruy Lopez, Schliemann Defense",
  C64: "Ruy Lopez, Classical Variation",
  C65: "Ruy Lopez, Berlin Defense",
  C66: "Ruy Lopez, Berlin Defense, 4.O-O d6",
  C67: "Ruy Lopez, Berlin Defense, Rio de Janeiro Variation",
  C68: "Ruy Lopez, Exchange Variation",
  C69: "Ruy Lopez, Exchange, Gligoric Variation",
  C70: "Ruy Lopez, Morphy Defense",
  C71: "Ruy Lopez, Morphy Defense, Deferred Steinitz Variation",
  C72: "Ruy Lopez, Morphy Defense, Modern Steinitz Defense",
  C73: "Ruy Lopez, Modern Steinitz Defense, Richter Variation",
  C74: "Ruy Lopez, Modern Steinitz Defense",
  C75: "Ruy Lopez, Modern Steinitz Defense, 5.c3",
  C76: "Ruy Lopez, Modern Steinitz Defense, Fianchetto Variation",
  C77: "Ruy Lopez, Morphy Defense",
  C78: "Ruy Lopez, Archangel Variation",
  C79: "Ruy Lopez, Steinitz Defense Deferred",
  C80: "Ruy Lopez, Open Variation",
  C81: "Ruy Lopez, Open, Howell Attack",
  C82: "Ruy Lopez, Open, 9.c3",
  C83: "Ruy Lopez, Open, Classical Defense",
  C84: "Ruy Lopez, Closed Variation",
  C85: "Ruy Lopez, Exchange Variation Declined",
  C86: "Ruy Lopez, Worrall Attack",
  C87: "Ruy Lopez, Closed, Averbakh Variation",
  C88: "Ruy Lopez, Closed, Anti-Marshall",
  C89: "Ruy Lopez, Marshall Attack, Main Line",
  C90: "Ruy Lopez, Closed, Pilnik Variation",
  C91: "Ruy Lopez, Closed, Smyslov Defense",
  C92: "Ruy Lopez, Closed, 9.h3",
  C93: "Ruy Lopez, Closed, Smyslov Defense",
  C94: "Ruy Lopez, Closed, Breyer Defense, Zaitsev Hybrid",
  C95: "Ruy Lopez, Closed, Breyer Defense",
  C96: "Ruy Lopez, Closed, Chigorin Defense",
  C97: "Ruy Lopez, Closed, Chigorin Defense, 12.a4",
  C98: "Ruy Lopez, Closed, Chigorin Defense, 12.Nf1",
  C99: "Ruy Lopez, Closed, Chigorin Defense, Main Line",

  // ── D: Closed / Semi-closed games ─────────────────────────────
  D00: "Queen's Pawn Opening",
  D01: "Rapport-Jobava System",
  D02: "Queen's Pawn Game, London System",
  D03: "Torre Attack",
  D04: "Queen's Pawn Opening, 2.Nf3 Nf6",
  D05: "Queen's Pawn, Yusupov-Rubinstein System",
  D06: "Queen's Gambit",
  D07: "Queen's Gambit Declined, Chigorin Defense",
  D08: "Queen's Gambit Declined, Albin Counter-Gambit",
  D09: "Queen's Gambit Declined, Albin Counter-Gambit, 5.g3",
  D10: "Queen's Gambit Declined Slav Defense",
  D11: "Queen's Gambit Declined Slav, 3.Nf3",
  D12: "Queen's Gambit Declined Slav, Exchange Variation",
  D13: "Queen's Gambit Declined Slav, Exchange Variation",
  D14: "Queen's Gambit Declined Slav, Exchange Variation",
  D15: "Queen's Gambit Declined Slav Defense",
  D16: "Queen's Gambit Declined Slav, Bronstein Variation",
  D17: "Queen's Gambit Declined Slav, Czech Variation",
  D18: "Queen's Gambit Declined Slav, Dutch Variation",
  D19: "Queen's Gambit Declined Slav, Dutch Variation, Main Line",
  D20: "Queen's Gambit Accepted",
  D21: "Queen's Gambit Accepted, 3.Nf3",
  D22: "Queen's Gambit Accepted, Alekhine Defense",
  D23: "Queen's Gambit Accepted",
  D24: "Queen's Gambit Accepted, 4.Nc3",
  D25: "Queen's Gambit Accepted, 4.e3",
  D26: "Queen's Gambit Accepted, Classical Variation",
  D27: "Queen's Gambit Accepted, Classical, 6.O-O",
  D28: "Queen's Gambit Accepted, Classical, 7.Qe2",
  D29: "Queen's Gambit Accepted, Classical, 8...Bb7",
  D30: "Queen's Gambit Declined",
  D31: "Queen's Gambit Declined, Semi-Slav Defense",
  D32: "Queen's Gambit Declined, Tarrasch Defense",
  D33: "Queen's Gambit Declined, Tarrasch, Schlechter-Rubinstein",
  D34: "Queen's Gambit Declined, Tarrasch Defense, 7.Bd3",
  D35: "Queen's Gambit Declined, Exchange Variation",
  D36: "Queen's Gambit Declined, Exchange, Positional Line",
  D37: "Queen's Gambit Declined, 4.Nf3",
  D38: "Queen's Gambit Declined, Ragozin Variation",
  D39: "Queen's Gambit Declined, Ragozin, Vienna Variation",
  D40: "Queen's Gambit Declined, Semi-Tarrasch Defense",
  D41: "Queen's Gambit Declined, Semi-Tarrasch, 5.cxd5",
  D42: "Queen's Gambit Declined, Semi-Tarrasch, 7.Bd3",
  D43: "Queen's Gambit Declined Semi-Slav Defense",
  D44: "Queen's Gambit Declined Semi-Slav, 5.Bg5 dxc4",
  D45: "Queen's Gambit Declined Semi-Slav, 5.e3",
  D46: "Queen's Gambit Declined Semi-Slav, 6.Bd3",
  D47: "Queen's Gambit Declined Semi-Slav, 7.Bc4",
  D48: "Queen's Gambit Declined Semi-Slav, Meran Variation",
  D49: "Queen's Gambit Declined Semi-Slav, Meran, 10.Ne4",
  D50: "Queen's Gambit Declined",
  D51: "Queen's Gambit Declined, Manhattan Variation",
  D52: "Queen's Gambit Declined, Cambridge Springs Variation",
  D53: "Queen's Gambit Declined, 4.Bg5",
  D54: "Queen's Gambit Declined, Anti-Neo-Orthodox Variation",
  D55: "Queen's Gambit Declined, 6.Nf3",
  D56: "Queen's Gambit Declined, Lasker Defense",
  D57: "Queen's Gambit Declined, Lasker Defense, Main Line",
  D58: "Queen's Gambit Declined, Tartakower Defense",
  D59: "Queen's Gambit Declined, Tartakower, Main Line",
  D60: "Queen's Gambit Declined, Orthodox Defense",
  D61: "Queen's Gambit Declined, Orthodox, Rubinstein Variation",
  D62: "Queen's Gambit Declined, Orthodox, 7.Qc2",
  D63: "Queen's Gambit Declined, Orthodox Defense, 7.Rc1",
  D64: "Queen's Gambit Declined, Orthodox, Rubinstein Attack",
  D65: "Queen's Gambit Declined, Orthodox, Rubinstein Attack, Main Line",
  D66: "Queen's Gambit Declined, Orthodox Defense, Bd3 Line",
  D67: "Queen's Gambit Declined, Orthodox Defense, Capablanca Freeing Maneuver",
  D68: "Queen's Gambit Declined, Orthodox Defense, Main Line",
  D69: "Queen's Gambit Declined, Orthodox Defense, Main Line, 13.de5",
  D70: "Grünfeld Defense",
  D71: "Grünfeld Defense, Russian Variation",
  D72: "Grünfeld Defense, Neo-Grünfeld, 5.cxd5 Nxd5, 7.O-O",
  D73: "Grünfeld Defense, Neo-Grünfeld, 6.cd5 Nd5, 7.O-O c5",
  D74: "Grünfeld Defense, Neo-Grünfeld, Nxd5, 7.O-O c5, 8.Nc3",
  D75: "Grünfeld Defense, Neo-Grünfeld, 6.cd5 Nd5, 7.O-O c5, 8.dxc5",
  D76: "Grünfeld Defense, Neo-Grünfeld, 6.cd5 Nd5, 7.O-O Nb6",
  D77: "Grünfeld Defense, Neo-Grünfeld, 6.O-O",
  D78: "Grünfeld Defense, Neo-Grünfeld, 6.O-O c6",
  D79: "Grünfeld Defense, Neo-Grünfeld, Main Line",
  D80: "Grünfeld Defense",
  D81: "Grünfeld Defense, Russian Variation, 6.Nf3",
  D82: "Grünfeld Defense, 4.Bf4",
  D83: "Grünfeld Defense, Gebhardt Gambit",
  D84: "Grünfeld Defense, Exchange, 5.Nxd5",
  D85: "Grünfeld Defense, Exchange Variation",
  D86: "Grünfeld Defense, Exchange, Classical Variation",
  D87: "Grünfeld Defense, Exchange, Spassky Variation",
  D88: "Grünfeld Defense, Exchange, Spassky Variation, Main Line",
  D89: "Grünfeld Defense, Exchange, Spassky Variation, 13.Bd3",
  D90: "Grünfeld Defense, Flohr Variation",
  D91: "Grünfeld Defense, Smyslov Russian Variation",
  D92: "Grünfeld Defense, 5.Bf4",
  D93: "Grünfeld Defense, 5.Bf4 O-O 6.e3",
  D94: "Grünfeld Defense, 5.e3",
  D95: "Grünfeld Defense, 5.e3 O-O 6.Qb3",
  D96: "Grünfeld Defense, Russian Variation",
  D97: "Grünfeld Defense, Russian Variation, Classical",
  D98: "Grünfeld Defense, Russian Variation, Classical, 9.Nb3",
  D99: "Grünfeld Defense, Russian Variation, Smyslov, 10.Bg5",

  // ── E: Indian / Catalan ───────────────────────────────────────
  E00: "Catalan Opening",
  E01: "Catalan Opening, Closed",
  E02: "Catalan Opening, Open, 5.Qa4",
  E03: "Catalan Opening, Open Defense",
  E04: "Catalan Opening, Open, 5.Nf3",
  E05: "Catalan Opening, Open, Classical Line",
  E06: "Catalan Opening, Closed, 5.Nf3",
  E07: "Catalan Opening, Closed, 6...Nbd7",
  E08: "Catalan Opening, Closed, 7.Qc2",
  E09: "Catalan Opening, Closed, Main Line",
  E10: "Queen's Pawn Opening",
  E11: "Bogo-Indian Defense",
  E12: "Queen's Indian Defense",
  E13: "Queen's Indian Defense, 4.Nc3",
  E14: "Queen's Indian Defense, 4.e3",
  E15: "Queen's Indian Defense, 4.g3",
  E16: "Queen's Indian Defense, Capablanca Variation",
  E17: "Queen's Indian Defense, Old Main Line",
  E18: "Queen's Indian Defense, Old Main Line, 7.Nc3",
  E19: "Queen's Indian Defense, Old Main Line, 9.Qxc3",
  E20: "Nimzo-Indian Defense",
  E21: "Nimzo-Indian Defense, Three Knights Variation",
  E22: "Nimzo-Indian Defense, Spielmann Variation",
  E23: "Nimzo-Indian Defense, Spielmann, 4.Qb3",
  E24: "Nimzo-Indian Defense, Sämisch Variation",
  E25: "Nimzo-Indian Defense, Sämisch, Keres Variation",
  E26: "Nimzo-Indian Defense, Sämisch Variation",
  E27: "Nimzo-Indian Defense, Sämisch, 5...O-O",
  E28: "Nimzo-Indian Defense, Sämisch, 6.e3",
  E29: "Nimzo-Indian Defense, Sämisch, Main Line",
  E30: "Nimzo-Indian Defense, Leningrad Variation",
  E31: "Nimzo-Indian Defense, Leningrad, Main Line",
  E32: "Nimzo-Indian Defense, Classical Variation",
  E33: "Nimzo-Indian Defense, Classical, 4...Nc6",
  E34: "Nimzo-Indian Defense, Classical, Noa Variation",
  E35: "Nimzo-Indian Defense, Classical, Noa Variation, 5.cxd5",
  E36: "Nimzo-Indian Defense, Classical, Botvinnik Variation",
  E37: "Nimzo-Indian Defense, Classical, Botvinnik, Main Line",
  E38: "Nimzo-Indian Defense, Classical, 4...c5",
  E39: "Nimzo-Indian Defense, Classical, 4...c5, Main Line",
  E40: "Nimzo-Indian Defense, 4.e3",
  E41: "Nimzo-Indian Defense, 4.e3 c5",
  E42: "Nimzo-Indian Defense, 4.e3 c5, 5.Ne2 (Rubinstein)",
  E43: "Nimzo-Indian Defense, Fischer Variation",
  E44: "Nimzo-Indian Defense, Fischer Variation, 5.Ne2",
  E45: "Nimzo-Indian Defense, 4.e3, Bronstein Variation",
  E46: "Nimzo-Indian Defense, 4.e3 O-O 5.Ne2",
  E47: "Nimzo-Indian Defense, 4.e3 O-O 5.Bd3",
  E48: "Nimzo-Indian Defense, 4.e3 O-O 5.Bd3 d5",
  E49: "Nimzo-Indian Defense, 4.e3 O-O 5.Bd3 d5, Botvinnik Variation",
  E50: "Nimzo-Indian Defense, 4.e3 O-O 5.Nf3 d6",
  E51: "Nimzo-Indian Defense, 4.e3 O-O 5.Nf3 d5",
  E52: "Nimzo-Indian Defense, 4.e3 O-O 5.Nf3 d5, 6.Bd3",
  E53: "Nimzo-Indian Defense, 4.e3 O-O 5.Nf3 d5, 7.O-O",
  E54: "Nimzo-Indian Defense, 4.e3 O-O 5.Nf3 d5, 7.O-O dxc4",
  E55: "Nimzo-Indian Defense, 4.e3 O-O 5.Nf3 d5, Bronstein Variation",
  E56: "Nimzo-Indian Defense, Main Line, 7...Nc6",
  E57: "Nimzo-Indian Defense, Main Line, 7...Nc6, 8.a3 dxc4 9.Bxc4",
  E58: "Nimzo-Indian Defense, Main Line, 7...Nc6, 8.a3",
  E59: "Nimzo-Indian Defense, Main Line, 7...Nc6, 8.a3 Bxc3 9.bxc3",
  E60: "King's Indian Defense",
  E61: "King's Indian Defense, 3.Nc3",
  E62: "King's Indian Defense, Fianchetto Variation",
  E63: "King's Indian Defense, Fianchetto, Panno Variation",
  E64: "King's Indian Defense, Fianchetto, Yugoslav System",
  E65: "King's Indian Defense, Fianchetto, Yugoslav, 7.O-O",
  E66: "King's Indian Defense, Fianchetto, Yugoslav Panno",
  E67: "King's Indian Defense, Fianchetto, Classical Variation",
  E68: "King's Indian Defense, Fianchetto, Classical, 8.d5",
  E69: "King's Indian Defense, Fianchetto, Classical Main Line",
  E70: "King's Indian Defense, 4.e4",
  E71: "King's Indian Defense, Makogonov System",
  E72: "King's Indian Defense, Averbakh System",
  E73: "King's Indian Defense, Averbakh, 6.Be3",
  E74: "King's Indian Defense, Averbakh, 6.Be3 c5",
  E75: "King's Indian Defense, Averbakh, Main Line",
  E76: "King's Indian Defense, Four Pawns Attack",
  E77: "King's Indian Defense, Four Pawns Attack, 6.Be2",
  E78: "King's Indian Defense, Four Pawns Attack, with Be2 and Nf3",
  E79: "King's Indian Defense, Four Pawns Attack, Main Line",
  E80: "King's Indian Defense, Sämisch Variation",
  E81: "King's Indian Defense, Sämisch, 5...O-O",
  E82: "King's Indian Defense, Sämisch, Double Fianchetto",
  E83: "King's Indian Defense, Sämisch, 6...Nc6",
  E84: "King's Indian Defense, Sämisch, Panno Main Line",
  E85: "King's Indian Defense, Sämisch, Orthodox Variation",
  E86: "King's Indian Defense, Sämisch, Orthodox, 7.Nge2 c6",
  E87: "King's Indian Defense, Sämisch, Orthodox, 7.d5",
  E88: "King's Indian Defense, Sämisch, Orthodox, 7.d5 c6",
  E89: "King's Indian Defense, Sämisch, Orthodox Main Line",
  E90: "King's Indian Defense, 5.Nf3",
  E91: "King's Indian Defense, 6.Be2",
  E92: "King's Indian Defense, Classical Variation",
  E93: "King's Indian Defense, Petrosian System",
  E94: "King's Indian Defense, Orthodox Variation",
  E95: "King's Indian Defense, Orthodox, 7...Nbd7, 8.Re1",
  E96: "King's Indian Defense, Orthodox, 7...Nbd7, Main Line",
  E97: "King's Indian Defense, Orthodox, Aronin-Taimanov Defense",
  E98: "King's Indian Defense, Orthodox, Taimanov Variation",
  E99: "King's Indian Defense, Orthodox, Taimanov, Main Line",
};
